#! ruby
require 'test/unit'

require 'rbon'
require './test/data.rb'

class TestIO < Test::Unit::TestCase
  def test_io
    dumpfile = 'tmp/N.dump'

    dumper = RBON::Dump.new
    File.open(dumpfile, 'w') do |dump|
      dumper.dump(N, io:dump)
    end

    items = nil
    loader = RBON::Load.new
    File.open(dumpfile, 'r') do |dump|
      items = loader.load(dump)
    end

    assert_equal N, items
    File.unlink dumpfile
  end
end
